name: diff
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
      - transformers>=4.25.1
      - accelerate
      - torchvision
      - ftfy
      - tensorboard
      - modelcards
      - bitsandbytes
      - gradio
      - natsort
      - safetensors
      - triton==2.0.0.dev20230208
      - transformers
      - bitsandbytes
      - xformers==0.0.17.dev444
      - git+https://github.com/ShivamShrirao/diffusers.git#egg=diffusers
# export LD_LIBRARY_PATH=/opt/conda/envs/diff/lib/python3.8/site-packages/nvidia/cublas/lib/:$LD_LIBRARY_PATH
variables:
  LD_LIBRARY_PATH: /opt/conda/envs/diff/lib/python3.8/site-packages/nvidia/cublas/lib/:/usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64
